repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@9.13.0
          - typescript@5.8.2
          - typescript-eslint@8.26.0
          - '@eslint/js@9.13.0'
          - '@stylistic/eslint-plugin@2.9.0'

  - repo: local
    hooks:
      - id: typescript-check
        name: typescript-check
        entry: npx tsc --noEmit
        language: node
        pass_filenames: false
        types: [ts]

      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types: [text]
        files: \.(ts|js|json|yaml|html|css)$
        additional_dependencies:
          - prettier@latest

      - id: lint-staged
        name: lint-staged
        entry: npx lint-staged
        language: node
        pass_filenames: false
        stages: [pre-commit]
        additional_dependencies:
          - lint-staged@latest
